---

- hosts: mons
  remote_user: root
  tasks:
    - name: Create Pools
      shell: "ceph osd pool create {{ item }} 64"
      with_items:
        - volumes 
        - images 
        - vms 
        - backups 
        - metrics 

    - name: Add auth user openstack
      shell: "ceph auth add client.openstack mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rwx pool=images, allow rwx pool=backups, allow rwx pool=metrics'"


